version: "3.9"

services:
  nuxt:
    build: .
    ports:
      - 80:3000
    expose:
      - 3000
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:12.3-alpine
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.3
    environment:
     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
     - PGADMIN_LISTEN_PORT=15432
    ports:
      - 15432:15432  
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
    postgres:
    pgadmin:
